"""remove policy number from users

Revision ID: 260208774cb0
Revises: 169fdf23cd36
Create Date: 2024-03-23 10:48:28.577810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260208774cb0'
down_revision = '169fdf23cd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_policy_number')
        batch_op.drop_column('policy_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_number', sa.VARCHAR(length=120), nullable=False))
        batch_op.create_index('ix_user_policy_number', ['policy_number'], unique=1)

    # ### end Alembic commands ###
