"""claims and images table

Revision ID: 3862ea4ba740
Revises: 260208774cb0
Create Date: 2024-03-23 10:55:59.341751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3862ea4ba740'
down_revision = '260208774cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_accident', sa.DateTime(), nullable=False),
    sa.Column('accident_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('injuries_reported', sa.Boolean(), nullable=False),
    sa.Column('damage_details', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_user_id'), ['user_id'], unique=False)

    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_claim_id'), ['claim_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_claim_id'))

    op.drop_table('image')
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_user_id'))

    op.drop_table('claim')
    # ### end Alembic commands ###
