name: Base pipeline

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ">=20.11"

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm run lint

            - name: Build
              run: pnpm run build

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
              env:
                  AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

            - name: Setup virtual environment
              run: |
                  python -m venv venv
                  source venv/bin/activate

            - name: Install Python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Test
              run: python -m pytest api/tests.py
